sudo: required
dist: trusty
addons:
  apt:
    sources:
      - google-chrome
    packages:
      - google-chrome-stable

language:
  - node_js
node_js:
  - stable
cache:
  yarn: true
  directories: node_modules
before_install:
  - export CHROME_BIN=chromium-browser
  - export DISPLAY=:99.0
  - sh -e /etc/init.d/xvfb start

script:
  - yarn test
after_success:
  - cat ./app/coverage/report/lcov.info | ./node_modules/.bin/coveralls