language:
  - node_js
node_js:
  - stable
cache:
  yarn: true
before_install:
  - export CHROME_BIN=chromium-browser
  - export DISPLAY=:99.0
  - sh -e /etc/init.d/xvfb start
script:
  - yarn test
after_success:
  - cat ./app/coverage/report/lcov.info | ./node_modules/.bin/coveralls